export const blogs = [
    {
        id:1,
        title:"This is a sample post with a very long title one that is even larger than would be normal for a title that can be shown",
        date:"6/6/2004",
        tags:["test-tag"],
        images:["/4430652.png"],
        links: [2,3],
    },
    {
        id:2,
        title:"This is a sample post 2",
        date:"6/9/2020",
        tags:["test-tag"],
        images:[],
        links: [],
    },
    {
        id:3,
        title:"This is a sample post 3",
        date:"10/5/2025",
        tags:[],
        images:[],
        links: [4,5],
    },
    {
        id:4,
        title:"This is a sample post 4",
        date:"10/5/2025",
        tags:["tag1","tag2"],
        images:[],
        links: [],
    },
    {
        id:5,
        title:"This is a sample post 5",
        date:"10/5/2025",
        tags:[],
        images:[],
        links: [],
    },
    //    {
    //         id:6,
    //         title:"This is a sample post 4",
    //         date:"10/5/2025",
    //         tags:["tag1","tag2"],
    //         images:[],
    //         links: [],
    //     },
    //     {
    //         id:7,
    //         title:"This is a sample post 4",
    //         date:"10/5/2025",
    //         tags:["tag1","tag2"],
    //         images:[],
    //         links: [],
    //     },
    //     {
    //         id:8,
    //         title:"This is a sample post 4",
    //         date:"10/5/2025",
    //         tags:["tag1","tag2"],
    //         images:[],
    //         links: [],
    //     },
    //     {
    //         id:9,
    //         title:"This is a sample post 4",
    //         date:"10/5/2025",
    //         tags:["tag1","tag2"],
    //         images:[],
    //         links: [],
    //     },
    //     {
    //         id:10,
    //         title:"This is a sample post 4",
    //         date:"10/5/2025",
    //         tags:["tag1","tag2"],
    //         images:[],
    //         links: [],
    //     },
]